// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func IndexPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html lang=\"en\"><head><script src=\"https://cdnjs.cloudflare.com/ajax/libs/htmx/2.0.4/htmx.min.js\" integrity=\"sha512-2kIcAizYXhIn8TzUvqzEDZNuDZ+aW7yE/+f1HJHXFjQcGNfv1kqzJSTBRBSlOgp6B/KZsz1K0a3ZTqP9dnxioQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script><!-- Cloudflare Web Analytics --><script defer src=\"https://static.cloudflareinsights.com/beacon.min.js\" data-cf-beacon=\"{&#34;token&#34;: &#34;ecf1c2ab13d340889669113d4169eb93&#34;}\"></script><!-- End Cloudflare Web Analytics --><script src=\"https://js.sentry-cdn.com/3c8f8e72313ce535044e76ae177a4614.min.js\" crossorigin=\"anonymous\"></script><meta charset=\"utf-8\"><link href=\"/static/css/style.css\" rel=\"stylesheet\"><script src=\"/static/js/main.js\"></script><title>x4132's img/ft</title></head><body class=\"dark bg-white text-black dark:bg-black dark:text-white\"><div class=\"mt-2 flex flex-col items-center pb-8\"><h1 class=\"text-4xl\">tfs-x4132</h1><div class=\"min-w-1/2 min-h-48 p-2 border flex flex-col justify-center items-center cursor-pointer\" id=\"fileBox\"><h3 class=\"text-xl\">Drag &amp; Drop or <a href=\"#\" id=\"selectFile\">Click to Select a File</a></h3><p>File uploads up to 200MB are permitted.</p></div><button id=\"uploadAll\" class=\"btn btn-upload mt-2\">Upload All</button><h3 class=\"mt-2\">Enter in an token:</h3><div class=\"flex items-center space-x-2\"><input id=\"authInput\" type=\"text\" class=\"border rounded-xl p-2 text-center\" placeholder=\"auth token\"> <button id=\"authButton\" class=\"btn btn-primary\">Auth</button></div></div><footer class=\"fixed bottom-0 left-0\"><span id=\"year\"></span>&nbsp;x4132.dev</footer><div id=\"dragModal\" class=\"hidden fixed top-0 left-0 bg-white/50 z-10 h-dvh w-dvw\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
